all:
	cd src && $(MAKE) all;
	echo make successful!;
clean:
	cd src && $(MAKE) clean;

cleanoutput:
	rm plot/* output/*;
	rm cstmpdir/*;
	rmdir cstmpdir;

cleantemp:
	rm *~ output/*~ mapping/*~ plot/*~ src/*~ namelist/*~
